version = 1

[[annotations]]
path = [
    "Tests/SpeziViewsTests/__Snapshots__/**",
    "Tests/UITests/TestApp/Resources/lukas_smol.png"
]
SPDX-FileCopyrightText = "2024 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"